import os
import time
print("安装进行中...")
print("安装版本:1.0,作者:YCJ(>.<)")
a = open("./data/wenjian/KG.txt", "r")
d = open("./data/wenjian/shop.txt", "r")
c = open("./data/wenjian/mod.txt", "r")
a1 = a.read()
d1 = d.read()
c1 = c.read()
print("已完成20%...")
time.sleep(1)
os.makedirs("./data/game/")
os.makedirs("./data/user/")
print("已完成50%...")
time.sleep(2)
open("./data/game/cundang.txt", "w", encoding="utf-8")
open("./data/game/cundang1.txt", "w", encoding="utf-8")
open("./data/user/name.txt", "w", encoding="utf-8")
b = open("./data/game/jinbi.txt", "w", encoding="utf-8")
b.write("0")
b.close()
print("已完成70%...")
time.sleep(3)
a2 = open("./KG游戏.py", "w", encoding="utf-8")
a2.write(a1)
a2.close()
d2 = open("./shop.py", "w", encoding="utf-8")
d2.write(d1)
d2.close()
c2 = open("./mod.py", "w", encoding="utf-8")
c2.write(c1)
c2.close()
print("已完成99%...")
time.sleep(3)
print("已完成100%...")
print("安装成功")
